[platformio]
src_dir = .

[env:m5stack_atom]
platform = espressif32
framework = arduino
board = m5stack-atom
build_flags =
	-D IR_TX_PIN=25
	-D CORE_DEBUG_LEVEL=3
build_src_filter = +<*> -<.git/> +<../IrBroadcast.h> +<../IrBroadcast.cpp> 
monitor_speed = 115200
lib_deps = 
	m5stack/M5Atom@^0.1.3
	fastled/FastLED@^3.6.0
